SCREENHEIGHT = 592
SCREENWIDTH = 1024

WAITTIME = 3000  

PICTUREHEIGHT = 800
PICTUREWIDTH = 600

LINECOLOUR = (226, 0, 89)
BACKGROUNDCOLOUR = (0, 0, 0)
LINEWIDTH = 2
IMPORTCOLOUR = (238, 127, 0)

AMPLITUDE = 90
SPEED = 1

LOCAL_DIR = "/home/pi/OutsideTheBox/N/PiDev/"

SWEEPFILE = LOCAL_DIR + "sweepFile.txt"
# in tagen
SWEEPTIME = 7
PRINT = 0
MOVE = 1
DELETE = 2
SWEEPMODE = DELETE
MOVEFOLDER = LOCAL_DIR + "deletedpics/"

FONT = LOCAL_DIR + "AblePro.otf"

LOGGING = False
BPM = LOCAL_DIR + "BPM/"
PICS = LOCAL_DIR + "pics/"
STATIONLOG = LOCAL_DIR + "stationlog.csv"
PICLOG = "LOG.TXT"
PULSELOG = "PULSE.TXT"
STDOUTLOG = LOCAL_DIR + "stdout.txt"

